export const countries = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "Côte d’Ivoire",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Rwanda",
  "São Tomé and Príncipe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
] as const;

export const DEFAULT_PROFILE_PICTURE =
  "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg";

export const newsCategories = [
  { value: "general-news", label: "General News" },
  { value: "tournament-updates", label: "Tournament Updates" },
  { value: "banned-updates", label: "Banned Player/Team Updates" },
  { value: "maintenance", label: "Maintenance Updates" },
  { value: "events", label: "Event Announcements" },
];

export const relatedEvents = [
  { value: "event1", label: "Summer Showdown 2024" },
  { value: "event2", label: "Fall Classic 2024" },
  { value: "event3", label: "Winter Cup 2024" },
  { value: "event4", label: "Spring Championship 2025" },
];
