// constants/phones.ts
//
// PURPOSE
//   Curated list of popular mobile phone models used to power the "Current Mobile Device"
//   type-to-search combobox on the Player Market post form (owner 2026-06-29, "Player
//   Available Post" feature 1). The combobox lets a player pick their phone quickly while
//   STILL allowing any free-text "Other" value, so the backend mobile_device CharField never
//   loses a phone that isn't on this list. This is FE UX only -- there is no schema change.
//
// COVERAGE (Africa-first, because that is the AFC player base)
//   Infinix, Tecno, itel, Samsung (Galaxy A / S / M / Note), Xiaomi / Redmi / POCO,
//   Apple iPhone (8 .. 16, incl. SE / Plus / Pro / Max), Realme, Oppo, vivo, Nokia,
//   Huawei, OnePlus, Motorola. ~300 models.
//
// CONNECTS TO
//   components/ui/phone-combobox.tsx (renders + filters this list; emits a string)
//   app/(user)/player-markets/page.tsx (Create/Edit Player form -> mobile_device)
//   backend afc_player_market/views.create_recruitment_post (stores the string, max 80 chars)
//
// NOTE: keep entries as the brand + model exactly as a player would recognise it; the search
// is punctuation/spacing tolerant on the component side, so "infinix note 30" finds "Infinix
// Note 30". Order roughly groups by brand for readability (the combobox sorts by match, not
// by array order).

export const PHONE_MODELS: string[] = [
  // ── Infinix ──────────────────────────────────────────────────────────────
  "Infinix Note 40 Pro+",
  "Infinix Note 40 Pro",
  "Infinix Note 40",
  "Infinix Note 30 Pro",
  "Infinix Note 30 VIP",
  "Infinix Note 30",
  "Infinix Note 12",
  "Infinix Note 12 Pro",
  "Infinix Note 11",
  "Infinix Note 11 Pro",
  "Infinix Note 10 Pro",
  "Infinix Note 10",
  "Infinix Note 8",
  "Infinix Zero 30 5G",
  "Infinix Zero 30",
  "Infinix Zero 20",
  "Infinix Zero Ultra",
  "Infinix Zero 8",
  "Infinix GT 20 Pro",
  "Infinix GT 10 Pro",
  "Infinix Hot 50 Pro+",
  "Infinix Hot 50 Pro",
  "Infinix Hot 50",
  "Infinix Hot 40 Pro",
  "Infinix Hot 40",
  "Infinix Hot 40i",
  "Infinix Hot 30",
  "Infinix Hot 30i",
  "Infinix Hot 30 Play",
  "Infinix Hot 20",
  "Infinix Hot 20i",
  "Infinix Hot 20 Play",
  "Infinix Hot 12",
  "Infinix Hot 12 Play",
  "Infinix Hot 11",
  "Infinix Hot 11s",
  "Infinix Hot 10",
  "Infinix Hot 10 Play",
  "Infinix Hot 9",
  "Infinix Smart 8",
  "Infinix Smart 8 Pro",
  "Infinix Smart 7",
  "Infinix Smart 6",
  "Infinix Smart 5",

  // ── Tecno ────────────────────────────────────────────────────────────────
  "Tecno Camon 30 Premier",
  "Tecno Camon 30 Pro",
  "Tecno Camon 30",
  "Tecno Camon 20 Premier",
  "Tecno Camon 20 Pro",
  "Tecno Camon 20",
  "Tecno Camon 19 Pro",
  "Tecno Camon 19",
  "Tecno Camon 18 Premier",
  "Tecno Camon 18",
  "Tecno Camon 17 Pro",
  "Tecno Camon 17",
  "Tecno Camon 16",
  "Tecno Camon 15",
  "Tecno Phantom V Fold",
  "Tecno Phantom V Flip",
  "Tecno Phantom X2 Pro",
  "Tecno Phantom X2",
  "Tecno Phantom X",
  "Tecno Spark 30 Pro",
  "Tecno Spark 30",
  "Tecno Spark 20 Pro+",
  "Tecno Spark 20 Pro",
  "Tecno Spark 20",
  "Tecno Spark 20C",
  "Tecno Spark 10 Pro",
  "Tecno Spark 10",
  "Tecno Spark 10C",
  "Tecno Spark 9 Pro",
  "Tecno Spark 9",
  "Tecno Spark 8 Pro",
  "Tecno Spark 8",
  "Tecno Spark 8C",
  "Tecno Spark 7",
  "Tecno Spark 7 Pro",
  "Tecno Spark 6",
  "Tecno Spark 5",
  "Tecno Pova 6 Pro",
  "Tecno Pova 6",
  "Tecno Pova 5 Pro",
  "Tecno Pova 5",
  "Tecno Pova 4 Pro",
  "Tecno Pova 4",
  "Tecno Pova 3",
  "Tecno Pova 2",
  "Tecno Pova Neo 3",
  "Tecno Pop 8",
  "Tecno Pop 7",
  "Tecno Pop 6 Pro",
  "Tecno Pop 5",

  // ── itel ─────────────────────────────────────────────────────────────────
  "itel S24",
  "itel S23+",
  "itel S23",
  "itel P55+",
  "itel P55",
  "itel P40",
  "itel A70",
  "itel A60s",
  "itel A60",
  "itel A50",
  "itel Vision 3",
  "itel Vision 2",
  "itel RS4",

  // ── Samsung Galaxy S ─────────────────────────────────────────────────────
  "Samsung Galaxy S24 Ultra",
  "Samsung Galaxy S24+",
  "Samsung Galaxy S24",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S23+",
  "Samsung Galaxy S23",
  "Samsung Galaxy S23 FE",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S22+",
  "Samsung Galaxy S22",
  "Samsung Galaxy S21 Ultra",
  "Samsung Galaxy S21+",
  "Samsung Galaxy S21",
  "Samsung Galaxy S21 FE",
  "Samsung Galaxy S20 Ultra",
  "Samsung Galaxy S20+",
  "Samsung Galaxy S20",
  "Samsung Galaxy S20 FE",
  "Samsung Galaxy S10+",
  "Samsung Galaxy S10",
  // ── Samsung Galaxy Note ──────────────────────────────────────────────────
  "Samsung Galaxy Note 20 Ultra",
  "Samsung Galaxy Note 20",
  "Samsung Galaxy Note 10+",
  "Samsung Galaxy Note 10",
  "Samsung Galaxy Note 9",
  // ── Samsung Galaxy A ─────────────────────────────────────────────────────
  "Samsung Galaxy A55",
  "Samsung Galaxy A35",
  "Samsung Galaxy A25",
  "Samsung Galaxy A15",
  "Samsung Galaxy A05s",
  "Samsung Galaxy A05",
  "Samsung Galaxy A54",
  "Samsung Galaxy A34",
  "Samsung Galaxy A24",
  "Samsung Galaxy A14",
  "Samsung Galaxy A04s",
  "Samsung Galaxy A04",
  "Samsung Galaxy A73",
  "Samsung Galaxy A53",
  "Samsung Galaxy A33",
  "Samsung Galaxy A23",
  "Samsung Galaxy A13",
  "Samsung Galaxy A72",
  "Samsung Galaxy A52s",
  "Samsung Galaxy A52",
  "Samsung Galaxy A32",
  "Samsung Galaxy A22",
  "Samsung Galaxy A12",
  "Samsung Galaxy A71",
  "Samsung Galaxy A51",
  "Samsung Galaxy A50",
  "Samsung Galaxy A21s",
  "Samsung Galaxy A11",
  "Samsung Galaxy A10s",
  "Samsung Galaxy A10",
  // ── Samsung Galaxy M ─────────────────────────────────────────────────────
  "Samsung Galaxy M55",
  "Samsung Galaxy M35",
  "Samsung Galaxy M34",
  "Samsung Galaxy M33",
  "Samsung Galaxy M32",
  "Samsung Galaxy M31",
  "Samsung Galaxy M14",
  "Samsung Galaxy M13",
  "Samsung Galaxy M12",
  // ── Samsung Galaxy Z ─────────────────────────────────────────────────────
  "Samsung Galaxy Z Fold 6",
  "Samsung Galaxy Z Flip 6",
  "Samsung Galaxy Z Fold 5",
  "Samsung Galaxy Z Flip 5",

  // ── Apple iPhone ─────────────────────────────────────────────────────────
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
  "iPhone 16 Plus",
  "iPhone 16",
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone 15 Plus",
  "iPhone 15",
  "iPhone 14 Pro Max",
  "iPhone 14 Pro",
  "iPhone 14 Plus",
  "iPhone 14",
  "iPhone 13 Pro Max",
  "iPhone 13 Pro",
  "iPhone 13",
  "iPhone 13 mini",
  "iPhone 12 Pro Max",
  "iPhone 12 Pro",
  "iPhone 12",
  "iPhone 12 mini",
  "iPhone 11 Pro Max",
  "iPhone 11 Pro",
  "iPhone 11",
  "iPhone SE (3rd gen)",
  "iPhone SE (2nd gen)",
  "iPhone XS Max",
  "iPhone XS",
  "iPhone XR",
  "iPhone X",
  "iPhone 8 Plus",
  "iPhone 8",

  // ── Xiaomi / Redmi / POCO ────────────────────────────────────────────────
  "Xiaomi 14 Ultra",
  "Xiaomi 14",
  "Xiaomi 13 Pro",
  "Xiaomi 13",
  "Xiaomi 12 Pro",
  "Xiaomi 12",
  "Xiaomi 11T Pro",
  "Xiaomi 11T",
  "Redmi Note 13 Pro+",
  "Redmi Note 13 Pro",
  "Redmi Note 13",
  "Redmi Note 12 Pro+",
  "Redmi Note 12 Pro",
  "Redmi Note 12",
  "Redmi Note 11 Pro",
  "Redmi Note 11",
  "Redmi Note 10 Pro",
  "Redmi Note 10",
  "Redmi Note 9 Pro",
  "Redmi Note 9",
  "Redmi 13C",
  "Redmi 12C",
  "Redmi 12",
  "Redmi 10C",
  "Redmi 10",
  "Redmi 9A",
  "Redmi 9C",
  "Redmi 9",
  "POCO X6 Pro",
  "POCO X6",
  "POCO X5 Pro",
  "POCO X5",
  "POCO X4 Pro",
  "POCO X3 Pro",
  "POCO X3 NFC",
  "POCO F6 Pro",
  "POCO F6",
  "POCO F5 Pro",
  "POCO F5",
  "POCO F4",
  "POCO M6 Pro",
  "POCO M5",
  "POCO C65",

  // ── Realme ───────────────────────────────────────────────────────────────
  "Realme 12 Pro+",
  "Realme 12 Pro",
  "Realme 12",
  "Realme 11 Pro+",
  "Realme 11 Pro",
  "Realme 11",
  "Realme 10 Pro+",
  "Realme 10 Pro",
  "Realme 10",
  "Realme 9 Pro+",
  "Realme 9 Pro",
  "Realme 9",
  "Realme 8 Pro",
  "Realme 8",
  "Realme C67",
  "Realme C55",
  "Realme C53",
  "Realme C35",
  "Realme C33",
  "Realme C31",
  "Realme C25",
  "Realme C21",
  "Realme GT 6",
  "Realme GT Neo 5",
  "Realme Narzo 60 Pro",
  "Realme Narzo 60",

  // ── Oppo ─────────────────────────────────────────────────────────────────
  "Oppo Find X7 Ultra",
  "Oppo Find X6 Pro",
  "Oppo Find N3 Flip",
  "Oppo Reno 11 Pro",
  "Oppo Reno 11",
  "Oppo Reno 10 Pro+",
  "Oppo Reno 10 Pro",
  "Oppo Reno 10",
  "Oppo Reno 8 Pro",
  "Oppo Reno 8",
  "Oppo Reno 7",
  "Oppo Reno 6",
  "Oppo A98",
  "Oppo A79",
  "Oppo A78",
  "Oppo A77",
  "Oppo A58",
  "Oppo A57",
  "Oppo A18",
  "Oppo A17",
  "Oppo A16",
  "Oppo A15",
  "Oppo A54",
  "Oppo A53",

  // ── vivo ─────────────────────────────────────────────────────────────────
  "vivo X100 Pro",
  "vivo X100",
  "vivo X90 Pro",
  "vivo V30 Pro",
  "vivo V30",
  "vivo V29",
  "vivo V27",
  "vivo V25",
  "vivo V23",
  "vivo Y100",
  "vivo Y36",
  "vivo Y35",
  "vivo Y27",
  "vivo Y22",
  "vivo Y21",
  "vivo Y20",
  "vivo Y17",
  "vivo Y16",
  "vivo Y15",
  "vivo T2 Pro",
  "vivo T2",

  // ── Nokia ────────────────────────────────────────────────────────────────
  "Nokia G42",
  "Nokia G22",
  "Nokia G21",
  "Nokia G11",
  "Nokia C32",
  "Nokia C31",
  "Nokia C22",
  "Nokia C21",
  "Nokia C12",
  "Nokia X30",
  "Nokia X20",
  "Nokia 5.4",
  "Nokia 3.4",

  // ── Huawei ───────────────────────────────────────────────────────────────
  "Huawei P60 Pro",
  "Huawei P50 Pro",
  "Huawei P40 Pro",
  "Huawei P40 lite",
  "Huawei P30 Pro",
  "Huawei P30 lite",
  "Huawei Mate 60 Pro",
  "Huawei Mate 50 Pro",
  "Huawei Mate 40 Pro",
  "Huawei Nova 12",
  "Huawei Nova 11",
  "Huawei Nova 10",
  "Huawei Nova 9",
  "Huawei Y9 Prime",
  "Huawei Y7p",
  "Huawei Y6p",

  // ── OnePlus ──────────────────────────────────────────────────────────────
  "OnePlus 12",
  "OnePlus 12R",
  "OnePlus 11",
  "OnePlus 10 Pro",
  "OnePlus 10T",
  "OnePlus 9 Pro",
  "OnePlus 9",
  "OnePlus 8T",
  "OnePlus Nord 3",
  "OnePlus Nord CE 3",
  "OnePlus Nord N30",
  "OnePlus Nord 2",

  // ── Motorola ─────────────────────────────────────────────────────────────
  "Motorola Edge 50 Pro",
  "Motorola Edge 40 Pro",
  "Motorola Edge 40",
  "Motorola Edge 30",
  "Motorola Moto G84",
  "Motorola Moto G54",
  "Motorola Moto G73",
  "Motorola Moto G53",
  "Motorola Moto G42",
  "Motorola Moto G32",
  "Motorola Moto G23",
  "Motorola Moto G22",
  "Motorola Moto G13",
  "Motorola Moto E13",
  "Motorola Moto E40",
  "Motorola Razr 40 Ultra",
  "Motorola Razr 40",
];
