"use client";

import { type Icon } from "@tabler/icons-react";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { type LucideIcon } from "lucide-react";
// i18n: the admin sidebar labels + the "Soon" badge are resolved from the
// adminNav namespace (messages/{en,fr,pt}/adminNav.json). Each nav item carries a
// `navKey` (see constants/nav-links.ts) that maps to a key in that file.
import { useTranslations } from "next-intl";

import {
  SidebarGroup,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from "@/components/ui/sidebar";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { useAuth } from "@/contexts/AuthContext";

export function NavMain({
  items,
}: {
  items: {
    label: string;
    // i18n key under the adminNav namespace; when present the visible label +
    // tooltip are resolved via t(navKey) instead of the raw English `label`.
    navKey?: string;
    slug: string;
    icon?: Icon | LucideIcon;
    comingSoon?: boolean;
    allowedRoles?: string[];
  }[];
}) {
  const pathname = usePathname();
  const { setOpenMobile } = useSidebar();
  const { user, isAdmin } = useAuth();
  // Admin-nav label translations (English authored in messages/en/adminNav.json,
  // fr/pt machine-generated by pnpm i18n:translate).
  const t = useTranslations("adminNav");

  const handleLinkClick = () => {
    setOpenMobile(false);
  };

  /**
   * Normalizes roles for comparison (e.g., "Head Admin" -> "head_admin")
   */
  const normalizeRole = (role: string) =>
    role.toLowerCase().replace(/\s+/g, "_");

  const canAccess = (linkAllowedRoles?: string[]) => {
    // 1. If user isn't logged in or isn't an admin at all, block.
    if (!user || !isAdmin) return false;

    // 2. Build the full set of roles (always include user.role + user.roles)
    const userRoles = [
      ...( Array.isArray(user.roles) ? user.roles.map(normalizeRole) : [] ),
      normalizeRole(user.role || ""),
    ].filter(Boolean);

    if (userRoles.includes("super_admin") || userRoles.includes("head_admin")) {
      return true;
    }

    // 3. Sponsors can ONLY see links explicitly tagged for them
    if (userRoles.includes("sponsor")) {
      return !!linkAllowedRoles?.includes("sponsor");
    }

    // 4. If no specific roles are required for the link, let them through
    if (!linkAllowedRoles || linkAllowedRoles.length === 0) return true;

    // 5. Check if any of the user's roles match the allowed roles
    return userRoles.some((role) => linkAllowedRoles.includes(role));
  };

  return (
    <SidebarGroup>
      <SidebarGroupContent className="flex flex-col gap-2">
        <SidebarMenu>
          {items
            .filter((item) => canAccess(item.allowedRoles))
            .map((item) => {
              const isActive =
                pathname === item.slug || pathname.startsWith(`${item.slug}/`);
              const IconComponent = item.icon;
              // Resolve the visible label from the item's i18n key (adminNav.*).
              // The authored English values are already the display form (e.g.
              // "Admin Dashboard" -> key "dashboard" -> "Dashboard"), so no
              // "Admin " prefix stripping is needed here. Fall back to the raw
              // English label (with the legacy strip) for any item without a navKey.
              const label = item.navKey
                ? t(item.navKey)
                : item.label.replace("Admin ", "");

              return (
                <SidebarMenuItem key={item.slug}>
                  {item.comingSoon ? (
                    <SidebarMenuButton
                      tooltip={label}
                      className="opacity-50 cursor-not-allowed"
                      disabled
                    >
                      {IconComponent && <IconComponent className="size-4" />}
                      <span>{label}</span>
                      <Badge variant="outline" className="ml-auto text-xs">
                        {t("soon")}
                      </Badge>
                    </SidebarMenuButton>
                  ) : (
                    <SidebarMenuButton
                      tooltip={label}
                      asChild
                      className={cn(
                        isActive &&
                          "bg-primary text-primary-foreground hover:bg-primary/90 hover:text-primary-foreground",
                      )}
                    >
                      <Link href={item.slug} onClick={handleLinkClick}>
                        {IconComponent && <IconComponent className="size-4" />}
                        <span>{label}</span>
                      </Link>
                    </SidebarMenuButton>
                  )}
                </SidebarMenuItem>
              );
            })}
        </SidebarMenu>
      </SidebarGroupContent>
    </SidebarGroup>
  );
}
