/**
 * i18n/request.ts — next-intl per-request configuration.
 *
 * Purpose: on every server request, work out which locale to render and hand
 * next-intl the merged message catalog for that locale. Wired into Next.js by
 * createNextIntlPlugin('./i18n/request.ts') in next.config.ts, so it runs for
 * every page/layout render automatically.
 *
 * How it connects to the rest of the system:
 *  - Reads the NEXT_LOCALE cookie (set by the language switcher in Phase 0) via
 *    cookies() from next/headers; falls back to DEFAULT_LOCALE ('en').
 *  - Loads + DEEP-MERGES every namespace JSON under messages/en/*.json and
 *    messages/<locale>/*.json, so any key missing in fr/pt falls back to the
 *    English string instead of showing the raw key.
 *  - The returned { locale, messages } is consumed server-side by getLocale()/
 *    getMessages() (used in app/layout.tsx) and surfaced to Client Components
 *    through components/I18nProvider → NextIntlClientProvider → useTranslations().
 *
 * Routing model: cookie-based, NO URL prefix and NO i18n middleware. Because no
 * middleware runs, next-intl REQUIRES us to return `locale` explicitly here.
 */

import { getRequestConfig } from "next-intl/server";
import { cookies } from "next/headers";
import { DEFAULT_LOCALE, isLocale, type Locale } from "./config";

// The cookie the language switcher writes and we read here. NEXT_LOCALE is also
// next-intl's own default cookie name, so the convention stays consistent.
const LOCALE_COOKIE = "NEXT_LOCALE";

/**
 * Recursively merge `override` onto `base`, returning a new object. Nested
 * objects are merged key-by-key; any leaf present in `override` wins, and any
 * leaf missing from `override` keeps the `base` (English) value. This is what
 * makes English the fallback for partially-translated fr/pt bundles.
 */
function deepMerge(
  base: Record<string, unknown>,
  override: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...base };
  for (const key of Object.keys(override)) {
    const baseVal = base[key];
    const overrideVal = override[key];
    if (
      isPlainObject(baseVal) &&
      isPlainObject(overrideVal)
    ) {
      // Both sides are objects → recurse so we merge per-key, not replace.
      out[key] = deepMerge(baseVal, overrideVal);
    } else {
      // Leaf value (string/number/array) → the override (locale) value wins.
      out[key] = overrideVal;
    }
  }
  return out;
}

// True only for "ordinary" objects (the shape namespace JSON files use). Arrays
// and null are intentionally excluded so they are treated as replaceable leaves.
function isPlainObject(value: unknown): value is Record<string, unknown> {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value)
  );
}

/**
 * Build the merged message catalog for a locale by reading the JSON files off
 * disk with node:fs (this module only ever runs on the server). We read from
 * disk rather than using webpack's dynamic import() because the fr/pt files may
 * not exist yet (they are generated by scripts/i18n-translate.mjs), and a
 * dynamic-import context that matches zero files breaks the build. fs.readFile
 * just returns "missing" cleanly, so partial translations degrade gracefully.
 *
 * Result shape: { <namespace>: { ...keys }, ... } — each top-level key is a
 * namespace (the file name without .json), which is what useTranslations('<ns>')
 * selects on the client.
 */
async function loadMessages(locale: Locale): Promise<Record<string, unknown>> {
  const { readFile } = await import("node:fs/promises");
  const path = await import("node:path");
  const root = path.join(process.cwd(), "messages");

  // The namespace list is derived from the English source, which is canonical.
  const namespaces = await getNamespaces();

  // Read + parse a single namespace JSON, returning {} if the file is absent
  // (e.g. an fr/pt namespace that has not been translated yet).
  const readNs = async (
    loc: string,
    ns: string,
  ): Promise<Record<string, unknown>> => {
    try {
      const raw = await readFile(path.join(root, loc, `${ns}.json`), "utf8");
      const parsed = JSON.parse(raw);
      return isPlainObject(parsed) ? parsed : {};
    } catch {
      // Missing file or invalid JSON → fall back to the English base.
      return {};
    }
  };

  let merged: Record<string, unknown> = {};

  for (const ns of namespaces) {
    // English base for this namespace (always present — it is the source).
    const enJson = await readNs(DEFAULT_LOCALE, ns);

    if (locale === DEFAULT_LOCALE) {
      // English request: no overlay needed, just nest the namespace.
      merged[ns] = enJson;
      continue;
    }

    // Locale overlay; a missing fr/pt file means the whole namespace falls back
    // to English. Deep-merge so per-key fallback works inside the namespace too.
    const localeJson = await readNs(locale, ns);
    merged[ns] = deepMerge(enJson, localeJson);
  }

  return merged;
}

// Cached namespace list. Computed once per server process by reading the
// English messages directory so we never hardcode the namespace names — adding
// messages/en/<new>.json is picked up automatically on the next cold start.
let cachedNamespaces: string[] | null = null;

async function getNamespaces(): Promise<string[]> {
  if (cachedNamespaces) return cachedNamespaces;
  // Use fs at request-config time (server only) to enumerate messages/en. This
  // file never runs in the browser, so importing node:fs/path here is safe.
  const { readdir } = await import("node:fs/promises");
  const path = await import("node:path");
  const dir = path.join(process.cwd(), "messages", "en");
  const entries = await readdir(dir);
  cachedNamespaces = entries
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
  return cachedNamespaces;
}

export default getRequestConfig(async () => {
  // Resolve the active locale from the NEXT_LOCALE cookie, validating it
  // against LOCALES. Anything unrecognised (or absent) falls back to English.
  const store = await cookies();
  const cookieValue = store.get(LOCALE_COOKIE)?.value;
  const locale: Locale = isLocale(cookieValue) ? cookieValue : DEFAULT_LOCALE;

  const messages = await loadMessages(locale);

  // `locale` MUST be returned because there is no i18n middleware in this
  // cookie-based setup (next-intl errors otherwise).
  // A fixed timeZone is set so next-intl date/number formatting is identical on the
  // server and the client (no hydration mismatch). UTC matches the Django backend
  // (settings.TIME_ZONE = "UTC").
  return { locale, messages, timeZone: "UTC" };
});
