"use client";

// ─────────────────────────────────────────────────────────────────────────────
// OrganizerTourLauncher.tsx  -  the "Take a tour" guide for the organizer portal
// ----------------------------------------------------------------------------
// PURPOSE
//   The organizer-portal counterpart of the admin tour
//   (app/(a)/a/_components/AdminTourLauncher + AdminTour). It is a STEP-BY-STEP
//   walkthrough that highlights the real controls on an organizer page one at a
//   time, with Next / Back / Skip. It is pathname-aware: it shows the "Take a tour"
//   button (and auto-shows the tour on the first visit to a page) only on routes
//   that have a tour defined in ./organizer-tour-steps, and renders nothing else.
//
//   Unlike the admin tour, the popover COPY is internationalized: every title and
//   description is resolved through next-intl (useTranslations("organizer")) using
//   the key  tour.<pageKey>.<stepId>.title / .description  (the shared sidebar step
//   uses tour.sidebar.title / .description). The English source lives in
//   messages/en/organizer.json; fr/pt are machine-generated by the translate script.
//
// HOW IT CONNECTS
//   - MOUNTED BY: app/(organizer)/organizer/layout.tsx, in the portal header next to
//     the Log out control. Because that header is on every organizer page, the
//     launcher is too - it simply hides itself where no tour exists.
//   - STEPS + ROUTE MAP come from ./organizer-tour-steps (ORGANIZER_TOUR_STEPS +
//     resolveOrganizerTourPageKey). Each step targets a control by the
//     `[data-tour="org-…"]` hooks added on the organizer pages and on the sidebar
//     nav in the layout.
//   - TOUR LIBRARY: driver.js (the same dependency + import + config the admin tour
//     uses, app/(a)/a/_components/AdminTour.tsx). We import its base CSS once and
//     restyle ONLY our `.afc-org-tour` popover to the AFC dark/green theme below.
//
// PERSISTENCE
//   Completion is stored per page in localStorage under
//       afc_org_tour_<pageKey>_done   (value "1")
//   Set when the tour finishes, is skipped/closed, or is dismissed with Escape /
//   overlay click. Once set, the tour never auto-opens again for that page (the user
//   can still replay it from the "Take a tour" button).
//
// SAFETY / NON-INTERFERENCE
//   - Auto-show fires once, only if the flag is unset, only after the targets have
//     had a tick to mount (so we never spotlight nothing).
//   - Selectors that match no element, or steps whose i18n copy fails to resolve,
//     are dropped before driving, so a tour never throws on a changed layout.
//   - If a page has zero resolvable steps, start() no-ops instead of opening an
//     empty overlay.
//
// COPY RULES: NO em or en dashes in any user-facing string. (Comments may use the
// box-drawing dash above - that never renders to the user.)
// ─────────────────────────────────────────────────────────────────────────────

import * as React from "react";
import { usePathname } from "next/navigation";
import { useTranslations } from "next-intl";
import { driver, type Driver, type DriveStep } from "driver.js";
import "driver.js/dist/driver.css";
import { Button } from "@/components/ui/button";
import { IconHelpCircle } from "@tabler/icons-react";
import {
  ORGANIZER_TOUR_STEPS,
  resolveOrganizerTourPageKey,
  type OrganizerTourPageKey,
  type OrganizerTourStep,
} from "./organizer-tour-steps";

// A translator function shaped like next-intl's `t`. Captured at render time and
// handed to the imperative driver.js builder so it can resolve copy lazily.
type Translate = ReturnType<typeof useTranslations>;

// localStorage key for "this page's tour has been seen/dismissed". One place so the
// key format is defined exactly once.
const doneStorageKey = (pageKey: OrganizerTourPageKey) =>
  `afc_org_tour_${pageKey}_done`;

// Read the "already seen" flag. Wrapped in try/catch because localStorage can throw
// in private-mode / SSR-edge cases; we fail safe to "seen" so we never nag on error.
function hasSeenTour(pageKey: OrganizerTourPageKey): boolean {
  if (typeof window === "undefined") return true;
  try {
    return window.localStorage.getItem(doneStorageKey(pageKey)) === "1";
  } catch {
    return true;
  }
}

// Persist the "seen" flag. Swallows storage errors (quota / disabled) silently - 
// failing to remember is harmless, it just means the tour might auto-show again.
function setSeenTour(pageKey: OrganizerTourPageKey): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(doneStorageKey(pageKey), "1");
  } catch {
    /* storage unavailable - ignore */
  }
}

// Safe querySelector: returns null instead of throwing on a bad selector.
function safeQuery(selector: string): HTMLElement | null {
  try {
    return document.querySelector<HTMLElement>(selector);
  } catch {
    return null;
  }
}

// Resolve a step's i18n title + description. The shared sidebar step reads from the
// flat tour.sidebar.* keys; every other step reads tour.<pageKey>.<id>.*. Wrapped in
// try/catch so a missing key drops the step rather than throwing the whole tour.
function resolveCopy(
  t: Translate,
  pageKey: OrganizerTourPageKey,
  step: OrganizerTourStep,
): { title: string; description: string } | null {
  const base =
    step.id === "sidebar" ? "tour.sidebar" : `tour.${pageKey}.${step.id}`;
  try {
    return { title: t(`${base}.title`), description: t(`${base}.description`) };
  } catch {
    return null;
  }
}

// Click the INACTIVE Radix tab trigger inside the given tab-list container so the
// other tab's content mounts. Kept for parity with the admin tour (the organizer
// tours below do not currently use it, but new pages might). Fully guarded.
function activateInactiveTab(tabListSelector: string): void {
  const list = safeQuery(tabListSelector);
  if (!list) return;
  const inactive = list.querySelector<HTMLElement>(
    '[role="tab"][data-state="inactive"]',
  );
  inactive?.click();
}

// Turn our OrganizerTourStep[] into driver.js DriveStep[], resolving i18n copy and
// dropping any step whose target is missing (unless `lazy`) or whose copy fails to
// resolve. Mirrors AdminTour.buildSteps(), with the i18n lookup layered in.
function buildSteps(
  pageKey: OrganizerTourPageKey,
  steps: OrganizerTourStep[],
  t: Translate,
  getDriver: () => Driver | null,
): DriveStep[] {
  if (typeof document === "undefined") return [];
  const out: DriveStep[] = [];

  for (const s of steps) {
    // Non-lazy steps must currently resolve to a real element, else drop them.
    if (!s.lazy && !safeQuery(s.element)) continue;

    const copy = resolveCopy(t, pageKey, s);
    if (!copy) continue; // missing translation → skip rather than throw

    const driveStep: DriveStep = {
      // Lazy steps resolve their selector at highlight time (post tab-switch);
      // eager steps keep the plain selector string.
      element: s.lazy ? () => safeQuery(s.element) ?? document.body : s.element,
      popover: {
        title: copy.title,
        description: copy.description,
        side: s.side,
        align: s.align,
      },
    };

    // Tab-switch step: take over Next so we can mount the other tab first.
    if (s.activateInactiveTab) {
      const tabList = s.activateInactiveTab;
      driveStep.popover!.onNextClick = () => {
        activateInactiveTab(tabList);
        window.setTimeout(() => getDriver()?.moveNext(), 220);
      };
    }
    // Specific-tab switch: click one exact tab trigger, then advance.
    if (s.activateTab) {
      const target = s.activateTab;
      driveStep.popover!.onNextClick = () => {
        safeQuery(target)?.click();
        window.setTimeout(() => getDriver()?.moveNext(), 220);
      };
    }

    out.push(driveStep);
  }

  return out;
}

// ── useOrganizerTour: owns the driver.js instance + "seen" flag + start/stop ──
function useOrganizerTour(pageKey: OrganizerTourPageKey, t: Translate) {
  const driverRef = React.useRef<Driver | null>(null);
  // Keep the latest translator in a ref so the (stable) start() closure always
  // resolves copy with the current next-intl context.
  const tRef = React.useRef<Translate>(t);
  React.useEffect(() => {
    tRef.current = t;
  }, [t]);

  // Mark the page's tour as done (used by finish, skip, close, Escape).
  const markDone = React.useCallback(() => {
    setSeenTour(pageKey);
  }, [pageKey]);

  // Tear down any live driver instance (used on unmount / route change).
  const destroy = React.useCallback(() => {
    if (driverRef.current?.isActive()) driverRef.current.destroy();
    driverRef.current = null;
  }, []);

  // Start (or replay) the tour. Builds steps fresh each time so it always reflects
  // the CURRENT DOM. No-ops if nothing on the page can be highlighted.
  const start = React.useCallback(() => {
    const steps = buildSteps(
      pageKey,
      ORGANIZER_TOUR_STEPS[pageKey] ?? [],
      tRef.current,
      () => driverRef.current,
    );
    if (steps.length === 0) return; // nothing to show - do not open an empty overlay

    destroy(); // destroy a previous run before starting a new one

    const d = driver({
      // Same look + config the admin tour uses (AdminTour.tsx).
      animate: true,
      smoothScroll: true,
      overlayColor: "#09090b", // near-black, matches the dark portal background
      overlayOpacity: 0.7,
      stagePadding: 6,
      stageRadius: 8,
      allowClose: true, // Escape / overlay click can dismiss
      showProgress: true,
      progressText: "Step {{current}} of {{total}}",
      nextBtnText: "Next",
      prevBtnText: "Back",
      doneBtnText: "Done",
      popoverClass: "afc-org-tour", // themed in <OrganizerTourStyles/> below
      steps,
      // Fired whenever the tour ends for ANY reason (Done, Skip/close, Escape,
      // overlay click). Persist "seen" so it never auto-nags again.
      onDestroyed: () => {
        markDone();
        driverRef.current = null;
      },
    });

    driverRef.current = d;
    d.drive();
  }, [pageKey, destroy, markDone]);

  // Clean up if the component unmounts mid-tour.
  React.useEffect(() => destroy, [destroy]);

  return { start };
}

// ── OrganizerTourLauncher: the visible button + auto-show + theme ────────────
// Mounted once in the portal header. Resolves the route to a pageKey; when none
// exists it renders nothing. Otherwise it renders the "Take a tour" button and
// auto-opens the tour on the user's FIRST visit to that page.
export function OrganizerTourLauncher() {
  const pathname = usePathname();
  const t = useTranslations("organizer");
  // Map the route to a tour key; null means "no tour on this page".
  const pageKey = resolveOrganizerTourPageKey(pathname ?? "");

  return (
    <>
      {pageKey ? <OrganizerTourControls pageKey={pageKey} t={t} /> : null}
      {/* Inject the popover theme once regardless, so it is ready the moment a
          tour starts. It is scoped to .afc-org-tour and harmless elsewhere. */}
      <OrganizerTourStyles />
    </>
  );
}

// The button + first-visit auto-show. Split out so the hooks below only run when a
// tour actually exists for the current route (pageKey is non-null here).
function OrganizerTourControls({
  pageKey,
  t,
}: {
  pageKey: OrganizerTourPageKey;
  t: Translate;
}) {
  const { start } = useOrganizerTour(pageKey, t);

  // First-visit auto-show: open the tour once, only if not seen, after a short
  // delay so async page content (tables, cards, tabs) has mounted.
  React.useEffect(() => {
    if (hasSeenTour(pageKey)) return;
    const timer = window.setTimeout(() => {
      // Re-check in case the user already launched + dismissed it within the delay.
      if (!hasSeenTour(pageKey)) start();
    }, 700);
    return () => window.clearTimeout(timer);
  }, [pageKey, start]);

  return (
    <Button
      type="button"
      variant="outline"
      size="sm"
      onClick={start}
      aria-label={t("tour.button")}
    >
      <IconHelpCircle className="h-4 w-4" />
      {/* Label hides on very small screens to keep the header tidy; the icon +
          aria-label stay so the control is never lost. */}
      <span className="hidden sm:inline">{t("tour.button")}</span>
    </Button>
  );
}

// ── <OrganizerTourStyles>: scoped theme overrides for the driver.js popover ──
// driver.css gives a plain white popover; this restyles ONLY our .afc-org-tour
// popover to the AFC dark/green theme using the app's CSS variables (so it tracks
// the theme). Mirrors AdminTour's <AdminTourStyles/>.
function OrganizerTourStyles() {
  return (
    <style
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{
        __html: `
        /* Card body: dark surface, light text, rounded-md to match AFC cards. */
        .driver-popover.afc-org-tour {
          background-color: var(--card);
          color: var(--card-foreground);
          border: 1px solid var(--border);
          border-radius: 0.5rem;
          box-shadow: 0 10px 30px -10px rgba(0, 0, 0, 0.6);
          font-family: var(--font-dm-sans, "DM Sans", ui-sans-serif, system-ui, sans-serif);
          max-width: 320px;
        }
        /* Title: green/primary + bold, mirroring AFC page headings. */
        .driver-popover.afc-org-tour .driver-popover-title {
          color: var(--primary);
          font-size: 1rem;
          font-weight: 700;
        }
        /* Body copy: readable muted-light, comfortable line height. */
        .driver-popover.afc-org-tour .driver-popover-description {
          color: var(--card-foreground);
          opacity: 0.85;
          font-size: 0.8125rem;
          line-height: 1.5;
        }
        /* Step counter (Step X of Y): muted. */
        .driver-popover.afc-org-tour .driver-popover-progress-text {
          color: var(--muted-foreground);
          font-size: 0.75rem;
        }
        /* The little arrow that points at the target inherits the card colour. */
        .driver-popover.afc-org-tour .driver-popover-arrow-side-left.driver-popover-arrow { border-left-color: var(--card); }
        .driver-popover.afc-org-tour .driver-popover-arrow-side-right.driver-popover-arrow { border-right-color: var(--card); }
        .driver-popover.afc-org-tour .driver-popover-arrow-side-top.driver-popover-arrow { border-top-color: var(--card); }
        .driver-popover.afc-org-tour .driver-popover-arrow-side-bottom.driver-popover-arrow { border-bottom-color: var(--card); }
        /* Footer buttons: Next/Done as the green primary, Back as a subtle outline. */
        .driver-popover.afc-org-tour .driver-popover-footer button {
          border-radius: 0.375rem;
          font-size: 0.8125rem;
          font-weight: 500;
          text-shadow: none;
          padding: 0.35rem 0.7rem;
          transition: background-color 0.15s ease, opacity 0.15s ease;
        }
        .driver-popover.afc-org-tour .driver-popover-next-btn,
        .driver-popover.afc-org-tour .driver-popover-footer button.driver-popover-next-btn {
          background-color: var(--primary);
          color: var(--primary-foreground);
          border: 1px solid var(--primary);
        }
        .driver-popover.afc-org-tour .driver-popover-next-btn:hover {
          opacity: 0.9;
        }
        .driver-popover.afc-org-tour .driver-popover-prev-btn {
          background-color: transparent;
          color: var(--card-foreground);
          border: 1px solid var(--border);
        }
        .driver-popover.afc-org-tour .driver-popover-prev-btn:hover {
          background-color: rgba(255, 255, 255, 0.06);
        }
        /* The close (x) control: muted, brightens on hover. */
        .driver-popover.afc-org-tour .driver-popover-close-btn {
          color: var(--muted-foreground);
        }
        .driver-popover.afc-org-tour .driver-popover-close-btn:hover {
          color: var(--card-foreground);
        }
      `,
      }}
    />
  );
}
